// Code generated by github.com/edwarnicke/imports-gen DO NOT EDIT.
package imports

import (
	_ "bytes"
	_ "context"
	_ "encoding/base64"
	_ "encoding/json"
	_ "fmt"
	_ "github.com/CycloneDX/cyclonedx-go"
	_ "github.com/go-resty/resty/v2"
	_ "github.com/machinebox/graphql"
	_ "github.com/mitchellh/go-homedir"
	_ "github.com/package-url/packageurl-go"
	_ "github.com/spf13/cobra"
	_ "github.com/spf13/pflag"
	_ "github.com/spf13/viper"
	_ "io"
	_ "mime/multipart"
	_ "net/http"
	_ "os"
	_ "path/filepath"
	_ "strconv"
	_ "strings"
)
