FROM golang:1.25.0-alpine3.22@sha256:77dd832edf2752dafd030693bef196abb24dcba3a2bc3d7a6227a7a1dae73169 AS build-stage
WORKDIR /build
ENV CGO_ENABLED=0
COPY go.mod go.sum ./
COPY ./internal/imports ./internal/imports
RUN go build ./internal/imports
COPY . .
RUN apk add --update zip
ARG VERSION=not_versioned
RUN mkdir /$VERSION
RUN chmod +x ./build.sh
RUN ./build.sh darwin amd64
RUN ./build.sh solaris amd64
RUN for GOARCH in 386 amd64 arm; do \
    ./build.sh freebsd $GOARCH; done;
RUN for GOARCH in 386 amd64 arm arm64; do \
    ./build.sh linux $GOARCH; done;
RUN for GOARCH in 386 amd64; do \
    ./build.sh openbsd $GOARCH; done;
RUN for GOARCH in 386 amd64; do \
    ./build.sh windows $GOARCH; done;
RUN cd ../$VERSION; sha256sum * > sha256sums.txt