FROM golang:1.26.2-alpine3.23@sha256:f85330846cde1e57ca9ec309382da3b8e6ae3ab943d2739500e08c86393a21b1 AS build-stage
WORKDIR /build
ENV CGO_ENABLED=0
COPY go.mod go.sum ./
COPY ./internal/imports ./internal/imports
RUN go build ./internal/imports
COPY . .
RUN apk add --update zip
ARG VERSION=not_versioned
RUN mkdir /$VERSION
RUN chmod +x ./build.sh
RUN ./build.sh darwin amd64; \
    ./build.sh darwin arm64; \
    ./build.sh solaris amd64
RUN for GOARCH in 386 amd64 arm; do \
    ./build.sh freebsd $GOARCH; done;
RUN for GOARCH in 386 amd64 arm arm64; do \
    ./build.sh linux $GOARCH; done;
RUN for GOARCH in 386 amd64; do \
    ./build.sh openbsd $GOARCH; done;
RUN for GOARCH in 386 amd64; do \
    ./build.sh windows $GOARCH; done;
RUN cd ../$VERSION; sha256sum * > sha256sums.txt