on: [push]

name: Build Docker Image And Submit Metadata To Reliza Hub

jobs:
  build-cli:
    permissions:
      id-token: write
    name: Build And Push CLI
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit
        uses: relizaio/rearm-docker-action@bab125f296558fbda5c2018d13ff318435d54d8f # v1.12.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-cli
          rearm_api_id: ${{ secrets.REARM_API_ID }}
          rearm_api_key: ${{ secrets.REARM_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          enable_sbom: true
          source_code_sbom_type: 'other'
          enable_public_cosign_sigstore: 'true'
          enable_codeql: 'true'
          codeql_language: 'go'
          push_latest_tag: false
